### PR TITLE
Fixes for arc length calculation

### PR DESCRIPTION
**Pull request by jenskutilek**
... continued from #5

### CODE REVIEW

**Comment by anthrotype** [comment]
would you like to wait for the next fonttools release and require that?

or you could try to import calcQuadraticArcLength and if it except ImportError then use the estimate one, so it will still work (even if less precise) with older fonttools

**Comment by jenskutilek** [comment]
I think we can wait for the next fonttools release. This isn't very high priority as nobody missed quadratic curve support until now ;)

**Comment by anthrotype** [comment]
https://github.com/fonttools/fonttools/releases/tag/3.20.0

**Comment by justvanrossum** [comment]
> I think we can wait for the next fonttools release. This isn't very high priority as nobody missed quadratic curve support until now ;)

Quadratic support where exactly? The FlattenPen has always supported quadratics, just not natively and therefore slightly less efficient...

**Comment by jenskutilek** [comment]
Oops, @justvanrossum you're right of course, I forgot that BasePen handles quadratic curves automatically by converting to cubic.

**Comment by justvanrossum** [comment]
@jenskutilek, is this PR ready to be merged? Upon shallow inspection it looks good to me.

**Comment by anthrotype** [comment]
in setup.py install_requires we need to bump fonttools to >= 3.20.0 when that function was first defined

**Pull request merged**
